.travis.yml
root/CMakeLists.txt
root/io/io/TBufferMergerBenchmarks.cxx
root/math/genvector/Cartesian3DBenchmarks.cxx
root/math/genvector/Transform3DBenchmarks.cxx

* GenVectorBenchmark is disabled: on-going fixes on GenVector side

Fixes for existing benchmarks

---

root/interpreter/RunInterpreter.cxx
root/io/io/TBufferMergerBenchmarks.cxx
root/math/genvector/Transform3DBenchmarks.cxx
root/roofit/roofit/RooFitBinnedBenchmarks.cxx

Adding to faster KeepRunning c++11 loop for rootbenches and updating ROOTSYS for InterpreterBench (in case it was not correctly setuped before)

Adding to faster KeepRunning c++11 loop for rootbenches

---

.travis.yml

This way we can 'actually' test with other than default compilers.

Let travis override CXX and CC.

---

CMakeLists.txt

Moving CMake gbenchmark build part after initialization of CMAKE_BUILD_TYPE

Setting up CMake gbenchmark build part after initialization build type

---

root/CMakeLists.txt
root/pyroot/CMakeLists.txt
root/pyroot/PyROOTTest.h
root/pyroot/RunPyROOT.cxx

This patch allows us to benchmark pyroot by executing ctest and emit csv
files for plotting.

Add PyROOT to benchmarks

---

CMakeLists.txt
include/rootbench/RBConfig.h

The purpose of the file is to simplify the benchmarking code by
using the predefined settings.

Add a rootbench config file.

---

root/roofit/CMakeLists.txt
root/roofit/vectorisedPDFs/CMakeLists.txt
root/roofit/vectorisedPDFs/benchAddPdf.cxx
root/roofit/vectorisedPDFs/benchGauss.cxx
root/roofit/vectorisedPDFs/benchJohnson.cxx

- Add benchmarks for Gauss, Johnson and addition of PDFs.
- Benchmarks test vectorised/batched code against legacy for
- Function evaluation
- Likelihood computation
- Log-likelihood computation

[RF] Add benchmarks for a few vectorised PDFs.

---

root/tmva/tmva/CMakeLists.txt

Currently breaks with `-Dtmva=OFF`!

[TMVA] Exclude TMVA cross-validation benchmark if TMVA not enabled

---

README.md

updated the README.md to use "nproc" to automatically select the maximum numbers of processing units available at the time of build.

Added nproc for automatic selection of processing units

---

root/tree/dataframe/CMakeLists.txt
root/tree/dataframe/df102_NanoAODDimuonAnalysis.C
root/tree/dataframe/df102_NanoAODDimuonAnalysis.py

* Use nthreads argument for df102*.py benchmarks instead of
a flag to enable/disable imt
* Use smaller file with only the muon collections to improve reliability
in the CI and for faster download of the data

Refactor df102* benchmarks

---

root/tree/tree/TTreeBenchmarks.cxx

Problem is only visible when compiling with R__LESS_INCLUDES

Add missing include to TTreeBenchmarks.cxx

---

root/io/io/CMakeLists.txt
root/io/io/TFile_ATLAS_Benchmark.cxx
root/io/io/TFile_LHCb_Benchmarks.cxx
root/io/io/TFile_NanoAOD_Benchmarks.cxx

I add new compression/decompression benchmarks for files below:
- `lhcb_B2ppKK2011_md_noPIDstrip.root`
- `Run2012B_DoubleMuParked.root`
- `gg_data-zstd.root`

Add compression benchmarks for LHCb/NanoAOD/ATLAS files

---

root/io/io/TFile_CompressionBenchmarks_MainEvent.cxx

This `branch` variable really seems unused and I'm not aware of side-effects of `GetBranch` that we might be interested in here.
But I might very well be wrong. @oshadura are you the maintainer of these benchmarks?

Fix unused variable warning

---

root/tree/tree/RNTupleH1Benchmarks.cxx

Fix running time measurement such that both TTree and RNTuple benchmarks count as of the second event. Fixes #184 
Results should look more like this now
```
35: ---------------------------------------------------------------------------------------
35: Benchmark                                             Time             CPU   Iterations
35: ---------------------------------------------------------------------------------------
35: BM_RNTuple_H1/BM_RNTuple_H1LZ4/iterations:5       14605 us        14340 us            5
35: BM_RNTuple_H1/BM_RNTuple_H1ZLIB/iterations:5     108539 us       108198 us            5
35: BM_RNTuple_H1/BM_RNTuple_H1LZMA/iterations:5     812103 us       810074 us            5
35: BM_RNTuple_H1/BM_RNTuple_H1ZSTD/iterations:5      40349 us        40307 us …
```

Fix stopwatch in RNTuple benchmarks

---

root/tree/dataframe/CMakeLists.txt
root/tree/dataframe/rdataframe_asnumpy.py

There's now a comprehensive benchmark suite regarding `RDataFrame.AsNumpy`. There are two benchmark running almost a minute, however, I would love to see huge amounts of data read into memory. That's what we have to optimize for ML applications and friends. Here the runtimes:
```
--------------------------------------------------------------------------------------------------------- benchmark: 13 tests ----------------------------------------------------------------------------------------------------------
12: Name (time in ms)                                                Min                    Max                   Mean            StdDev                 Median               IQR            Outliers      OPS            Rounds  Iterations
12: …
```

[DF][PyROOT] Add AsNumpy benchmarks

---

root/tree/dataframe/CMakeLists.txt
root/tree/dataframe/RNTupleDSBenchmarks.cxx
root/tree/tree/CMakeLists.txt
root/tree/tree/RNTupleLHCBBenchmarks.cxx

Currently only running on uncompressed rntuple data, to accentuate the overhead of RNTupleDS.

Add RNTuple and RNTupleDS LHCB benchmarks

---

root/tree/dataframe/RDataFrameBenchmarks.cxx

Otherwise we end up accumulating a crazy amount of code to be jitted
that changes the runtime of the first subsequent event loop.
Unfortunately we cannot simply drop the code to be jitted because
it also needs to perform certain clean-up operations, see
https://sft.its.cern.ch/jira/browse/ROOT-10724.

[DF] Flush global cache of code-to-jit at benchmark end

---

cmake/modules/AddRootBench.cmake

Fixes root-project/rootbench#208

The rt library does not exist on osx.

---

root/roofit/vectorisedPDFs/benchAddPdf.cxx
root/roofit/vectorisedPDFs/benchJohnson.cxx

Call RooAddPdf::fixNormalizationCoefficient to avoid having tons of warning when evaluating the un-normalized RooAddPdf in the benchmark tests

Fix warnings messages when running RooFit benchmark tests 

---

root/roofit/vectorisedPDFs/benchAddPdf.cxx
root/roofit/vectorisedPDFs/benchJohnson.cxx

One needs to fix the normalisation of the RooAddPdf to avoid having tons of warning when evaluating the un-normalized RooAddPdf in the benchmark tests.

Call RooAddPdf::fixNormalizationCoefficient to avoid warning messages.

---

root/tree/dataframe/RDataFrameBenchmarks.cxx

Here are the results I got by running it locally. master vs https://github.com/root-project/root/pull/7651:
```
10: BM_RDataFrame_JitLargeGraphs/100                                  839628 us       832963 us            1
10: BM_RDataFrame_JitLargeGraphs/1000                                3170937 us      3165917 us            1
10: BM_RDataFrame_JitLargeGraphs/10000                              38968494 us     38905225 us            1
10: BM_RDataFrame_JitLargeGraphs/100                                  683157 us       677816 us            1
10: BM_RDataFrame_JitLargeGraphs/1000                                1284963 us      1282854 us            1
10: BM_RDataFrame_JitLargeGraphs/10000                              11771816 us     11750960 us            1
```

[DF] Add benchmark for jitting large DF graphs

---

root/tree/dataframe/CMakeLists.txt
root/tree/dataframe/RDataFrameOpenDataBenchmarks.cxx

These benchmarks use reduced data and the code from
https://github.com/stwunsch/opendata-benchmarks
Fixes root-project/root#7745
Here the runtime overview:
```
12: ----------------------------------------------------------------------------------------------
12: Benchmark                                                    Time             CPU   Iterations
12: ----------------------------------------------------------------------------------------------
12: BM_RDataFrame_OpenDataBenchmark1_jitted/0/repeats:1       4534 ms         4336 ms            1
12: BM_RDataFrame_OpenDataBenchmark1_jitted/8/repeats:1       1390 ms         1293 ms            1
12: BM_RDataFrame_OpenDataBenchmark2_jitted/0/repeats:1      10945 ms        10898 ms            1
12: …
```

[DF] Add opendata benchmarks

---

cmake/modules/GoogleBenchmark.cmake

In particular this fixes a compilation error in gbench with recent
gcc versions by adding a missing include in `benchmark_register.h`.

Bump google benchmark version to 1.5.5

---

root/roofit/vectorisedPDFs/SlowRooExponential.h
root/roofit/vectorisedPDFs/benchAddPdf.cxx

When a PDF doesn't provide a fast batch evaluation function
(evaluateSpan() overridden), a slower fallback is used. The benchmark
for Gauss + Exp using AddPdf is extended to include this fallback test.
Further, less iterations are run to speed up the overall execution time,
and parameter sets are precomputed in order to avoid starting and
stopping the benchmark timers.

[RF] Include evaluateSpan() fallback test in AddPdf benchmark.

---

root/roofit/vectorisedPDFs/CMakeLists.txt

This makes `rootbench` build again with the ROOT master.

[RF] Link vectorisedPDFs benchmarks with RooBatchCompute

---

root/tree/tree/RNTupleH1Benchmarks.cxx

According to RNTuple binary format v1 specification, [section std::vector<T> and ROOT::RVec<T>](https://github.com/root-project/root/blob/master/tree/ntuple/v7/doc/specifications.md#stdvector-and-rootrvec), the name of the child field of a `std::vector<T>` is now `_0`.
This PR fixes the dot-path in RNTupleH1Benchmarks.

[ntuple] Minor fix required after merging RNTuple binary format v1

---

root/math/genvector/Cartesian3DBenchmarks.cxx

I am not sure exactly why, but with the empty payload of
BM_Cartesian3D_Sanity google benchmark seems to enter an
infinite loop here:
https://github.com/google/benchmark/blob/d0fbf8ac238d3bc3a111334ab3553173812d78e7/src/benchmark_runner.cc#L280-L303
In principle gbench should exit the loop after a certain maximum
number of iterations, but it doesn't seem to happen, or for some
reason it takes way too much time.
In any case, as this benchmark is actually just a hack to inject a
sanity check, we might as well set it to run only 1 iteration.

Fix CI hanging at GenVector benchmark

---

root/tree/dataframe/RDataFrameOpenDataBenchmarks.cxx

Previously rootbench/root/tree/dataframe/RDataFrameOpenDataBenchmarks.cxx was outdated.
There are several imporvements in https://github.com/root-project/opendata-benchmarks,
which are now applied (in compiled, jitted and helping functions).
Main optimizations come from removing redundant variables/operations/etc.

Update to the latest RDataFrameOpenDataBenchmarks

---

root/tree/dataframe/RDataFrameOpenDataBenchmarks.cxx

All errors and warnings of RDataFrameOpenDataBenchmarks (introduced in #242) are now cleared.

Fix Errors in RDataFrameOpenDataBenchmarks

---

root/tree/dataframe/RDataFrameOpenDataBenchmarks.cxx

The helping function benchmark8_additional_lepton_idx is supposed to
reutn `unsigned int`.

[RDFODB] Quickfix compiled query 8

---

root/roofit/CMakeLists.txt
root/roofit/histfactory/CMakeLists.txt
root/roofit/histfactory/TestWorkspaces.cxx
root/roofit/histfactory/TestWorkspaces.h
root/roofit/histfactory/benchHistFactory.cxx

This is a follow up to https://github.com/root-project/root/pull/10562.
The benchmark measures the fit time for the model from the `hf001_example` tutorial.
Right now, the benchmark output looks as follows:
```
----------------------------------------------------------------------------------------------
Benchmark                                                    Time             CPU   Iterations
----------------------------------------------------------------------------------------------
hf001__BinnedFitOptimization_ON___BatchMode_OFF/1/0      0.180 ms        0.180 ms         3925
hf001__BinnedFitOptimization_OFF__BatchMode_OFF/0/0       1.25 ms         1.25 ms          553
hf001__BinnedFitOptimization_ON___BatchMode_ON_/1/1       1.29 ms         1.29 ms          518 …
```

[RF] Add HistFactory benchmark based of `hf001_example` tutorial

---

cmake/modules/AddRootBench.cmake
cmake/modules/RootBenchOptions.cmake

This allows natively to use the google tool compare.py, which expects json formatted google benchmarks.
Co-authored-by: Bertrand Bellenot <Bertrand.Bellenot@cern.ch>

[cmake] Allow user to specify json output fromat of the benchmarks

---

root/roofit/roofit/RooFitUnBinnedBenchmarks.cxx
root/roofit/vectorisedPDFs/benchAddPdf.cxx
root/roofit/vectorisedPDFs/benchFitModel.cxx
root/roofit/vectorisedPDFs/benchGauss.cxx
root/roofit/vectorisedPDFs/benchProdPdf.cxx

The RooFit unbinned benchmark is updated because the target for CHEP is to fully support it on the GPU.

[RF] Include BatchMode CPU and CUDA in RooFit unbinned benchmarks

---

root/roofit/vectorisedPDFs/benchAddPdf.cxx
root/roofit/vectorisedPDFs/benchGauss.cxx

It's not useful to benchmark this. It will always be slow because the results are copied. The GPU backend makes only sense in the context of likelihood minimization.

[RF] Don't benchmark model evaluation on GPU

---

root/roofit/roofit/RooFitUnBinnedBenchmarks.cxx
root/roofit/vectorisedPDFs/benchAddPdf.cxx
root/roofit/vectorisedPDFs/benchFitModel.cxx
root/roofit/vectorisedPDFs/benchGauss.cxx
root/roofit/vectorisedPDFs/benchJohnson.cxx
root/roofit/vectorisedPDFs/benchProdPdf.cxx
root/roofit/vectorisedPDFs/helpers.h

Before benchmarking a likelihood minimization, the model parameters need to be reset to something away from the parameters that were used to generate the toy dataset. Otherwise, the fit is starting already at the minimium and we won't benchmark the actual minimization path.
Furthermore, the parameters need to be reset after each benchmark iteration.

[RF] Reset parameters before fitting in `vectorizedPDFs` benchmarks

---

root/roofit/histfactory/benchHistFactory.cxx
root/roofit/roofit/RooFitBinnedBenchmarks.cxx
root/roofit/roofit/RooFitUnBinnedBenchmarks.cxx
root/roofit/roofit/benchCodeSquashAD.cxx
root/roofit/roofit/benchRooFitBackends.cxx

Sister PR of https://github.com/root-project/root/pull/12716

[RF] Adapt rootbench to new `RooFit::EvalBackend()` command argument

---

root/hist/hist/FitGradBenchmarks.cxx
root/hist/hist/TFormulaBenchmarks.cxx
root/hist/hist/THistFillBenchmarks.cxx
root/io/io/TBufferMergerBenchmarks.cxx
root/roofit/histfactory/benchHistFactory.cxx
root/roofit/roofit/RooFitBinnedBenchmarks.cxx
root/roofit/roofit/benchCodeSquashAD.cxx
root/tree/dataframe/LoopSUSYFrame/inc/LoopSUSYFrame/GenericHelpers.h
root/tree/dataframe/LoopSUSYFrame/inc/LoopSUSYFrame/LeptonHelpers.h
root/tree/dataframe/wmass/inc/getWeights.hpp

Apply `clang-tidy` suggestions

---

root/io/io/TBufferMergerBenchmarks.cxx
root/roofit/roofit/RooFitBinnedBenchmarks.cxx
root/roofit/roofit/benchCodeSquashAD.cxx
root/roofit/roofit/benchRooFitBackends.cxx

Avoid compiler warnings when building `rootbench`.

Avoid compiler warnings when building `rootbench`

---

root/roofit/histfactory/TestWorkspaces.cxx
root/roofit/histfactory/TestWorkspaces.h
root/roofit/histfactory/benchHistFactory.cxx
root/roofit/roofit/RooFitBinnedBenchmarks.cxx

Replace RooFit legacy iterators in `rootbench`, so that we can deprecate them at some point without causing warnings.

[RF] Replace RooFit legacy iterators and make code compile also with memory safe mode

---

root/tree/tree/gen_h1.cxx

`RFieldBase` was moved out of the `Detail` namespace, but it's not actually used by the code.

Remove unused using declaration from gen_h1

---

root/tree/dataframe/CMakeLists.txt
root/tree/dataframe/RNTupleDSBenchmarks.cxx
root/tree/tree/CMakeLists.txt
root/tree/tree/RNTupleH1Benchmarks.cxx
root/tree/tree/RNTupleLHCBBenchmarks.cxx
root/tree/tree/gen_h1.cxx

There is a new data file in the RNuple RC2 format available here:
https://cernbox.cern.ch/s/oMBJXfI0OHEpqy1
@dpiparo Could you copy the file to https://root.cern.ch/files/rootbench/

Fixes for latest RNTuple changes

---

.gitignore
root/roofit/CMakeLists.txt
root/roofit/atlas-benchmarks/roofitAtlasHiggsBenchmark.cxx

Update RooFit ATLAS benchmarks

---

root/roofit/histfactory/benchHistFactory.cxx

The interface to store and retrieve the minimization path was removed. It was not necessary anymore, because by now all backends that are benchmarked behave the same and therefore the minimizer follows the same minimization path.

Fix compilation of `benchHistFactory`

---

root/roofit/histfactory/TestWorkspaces.cxx

Avoid using `SetExportOnly`, which was deprecated in ROOT 6.34 and will be removed in ROOT 6.36

Avoid using deprecated `SetExportOnly`
