root-project/rootbench

CMakeLists.txt
cmake/modules/RootBenchOptions.cmake
root/math/genvector/Cartesian3DBenchmarks.cxx

Adding rootbench coverage and adjusting benchmark for templated class, making the coverage tools work perfectly.

Adding rootbench coverage

---

root/hist/hist/CMakeLists.txt
root/hist/hist/TFormulaGradientBenchmarks.cxx

@oshadura Is this what you wanted?

Benchmarked CLAD gradient tests

---

root/io/io/CMakeLists.txt
root/io/io/TFileBenchmarks.cxx

I am trying to develop a benchmark to measure the compression ratio of different algorithms. This works so far but I am still looking for how to measure file sizes with GoogleBenchmarks, since right now it only measures speeds.
Also, I am using RDF initial data to test the algorithms.

Initial work compression benchmark

---

.travis.yml
travis-scripts/coveralls.sh
travis-scripts/lcov-info-part1.sh
travis-scripts/lcov-info-part2.sh
travis-scripts/lcov-part1.sh
travis-scripts/lcov-part2.sh
travis-scripts/rootgcno.sh

Misc changed (making Travis happy)

[CI] Misc changes

---

cmake/modules/AddRootBench.cmake
pytest.ini

@oshadura Just merge if you are fine!

generate unique name for csv files from pytests

---

cmake/modules/AddRootBench.cmake
requirements.txt
tools/upload2influxdb.py

We are missing a few final push ups, like the name of the measurement and additional tags/flags provided by jenkins.
Relates to https://github.com/root-project/rootbench/issues/125 and https://github.com/root-project/rootbench/issues/122

Pytest integration and new procedure to upload results to Influx DB

---

tools/upload2influxdb.py

Add mechanic to detect data type

Fix upload script

---

cmake/modules/AddRootBench.cmake
root/tree/dataframe/CMakeLists.txt
root/tree/dataframe/df102_NanoAODDimuonAnalysis.py
root/tree/dataframe/rdataframe_asnumpy.py

Tadaa! :tada: 
@eguiraud @oshadura Please review! I may have done stupid things, although everything works fine for me :)

Refactor RB_ADD_PYTESTBENCHMARK and add RDF tutorial df102 as benchmark

---

root/tree/dataframe/wmass/CMakeLists.txt

This should fix rootbench's nightly builds.

[DF] Fix library dependencies of wmass benchmark

---

root/tree/dataframe/wmass/RDFprocessor/RDFtree.py
root/tree/dataframe/wmass/RDFprocessor/module.py

Fixing the `iteritems` differences between py2/py3.
Then, everything runs smoothly on my machine!

[RDF] Further py3 fixes for wmass benchmark

---

root/tree/dataframe/CMakeLists.txt
root/tree/dataframe/df103_NanoAODHiggsAnalysis.C
root/tree/dataframe/df103_NanoAODHiggsAnalysis.py

Runtime for each benchmark is 10s to 20s!

Add RDF tutorial df103 as cpp and py benchmark

---

root/tree/dataframe/wmass/CMakeLists.txt
root/tree/dataframe/wmass/runSignalAnalysis.py

I.e. let cling find the headers it needs.

[DF] Fix runtime errors in wmass benchmark

---

root/tree/dataframe/wmass/CMakeLists.txt
root/tree/dataframe/wmass/runSignalAnalysis.py

As requested by Andrea Rizzi and Danilo Piparo in CMS.

Use the same 10k events repeated 80 times for wmass benchmark

---

root/roofit/vectorisedPDFs/benchAddPdf.cxx
root/roofit/vectorisedPDFs/benchGauss.cxx
root/roofit/vectorisedPDFs/benchJohnson.cxx

Replace the deleted function calls with the new interface equivalent ones. Linked to https://github.com/root-project/root/pull/6841

[RF] Purge old batch Interface.

---

root/roofit/vectorisedPDFs/benchAddPdf.cxx
root/roofit/vectorisedPDFs/benchGauss.cxx
root/roofit/vectorisedPDFs/benchJohnson.cxx

Petty changes for compatibility with ROOT #6968.

[RF] Update names for compatibility with RooBatchCompute library.

---

root/hist/hist/CMakeLists.txt
root/hist/hist/FitGradBenchmarks.cxx
root/hist/hist/TFormulaBenchmarks.cxx
root/hist/hist/TFormulaGradientBenchmarks.cxx

Add new benchmark test for fitting using Gradient.
Move out single gaus fit to a new test, FitGrafBenchmark and add a new test fitting an histogram with a polynomial and
a variable number of gaussians.
The number of gaussians and number of bins can be specified by doing:
./FitGradBenchmark -nfunc 10 -nbins 1000
Fix also existing test fitting a single gaussian.

Improve fitting benchmark using AD or numerical gradient

---

root/hist/hist/TFormulaGradientBenchmarks.cxx

After changes in https://github.com/root-project/root/commit/16d6f31b7f9f0dab50bcab01056f75ed5fef5a2f#diff-102c2aaccb89dc266b3c2f7c87fe095da18d45d66915e3674184c5787c090d80  TF1::GradientPar also returns the CLAD gradient if the function has FeneratedGradient called it before.

Fix comparison test CLAD vs Numerical.

---

root/hist/hist/RHistFillBenchmarks.cxx
root/interpreter/RunInterpreterNoPCH.cxx
root/math/mathcore/TMathBenchmarks.cxx
root/tree/dataframe/LoopSUSYFrame/inc/LoopSUSYFrame/LeptonHelpers.h
root/tree/dataframe/LoopSUSYFrame/src/GenericHelpers.cxx
root/tree/dataframe/LoopSUSYFrame/src/LeptonHelpers.cxx
root/tree/dataframe/LoopSUSYFrame/src/main.cxx
root/tree/dataframe/LoopSUSYFrame/src/readFFXML.cxx
root/tree/dataframe/RDataFrameOpenDataBenchmarks.cxx
root/tree/dataframe/wmass/src/TH1weightsHelper.cpp
root/tree/dataframe/wmass/src/TH2weightsHelper.cpp
root/tree/dataframe/wmass/src/TH3weightsHelper.cpp
root/tree/dataframe/wmass/src/dataObs.cpp
root/tree/dataframe/wmass/src/getWeights.cpp
root/tree/tree/RNTupleLHCBBenchmarks.cxx

This PR should fix all the warnings that we see in the nightly builds.

Fix warnings

---

root/tree/dataframe/LoopSUSYFrame/src/LoopSUSYFrame.cxx
root/tree/dataframe/LoopSUSYFrame/src/readFFXML.cxx
root/tree/dataframe/wmass/src/getACValues.cpp
root/tree/dataframe/wmass/src/getWeights.cpp

This should make the nightlies green.

Fix warnings visible in nightly builds

---

root/roofit/histfactory/benchHistFactory.cxx

The same minimization path is now used for each configuration to ensure
a fair comparison.

[RF] Use reference minimization path in HistFactory benchmark

---

root/roofit/roofit/RooFitBinnedBenchmarks.cxx

Also don't go up to 4 channels or 20 bins anymore (it takes too
long...). We will just go up to 3 channels and 15 bins.

[RF] Refactor RooFitBinnedBenchmarks to avoid code duplication

---

root/io/io/CMakeLists.txt
root/tree/CMakeLists.txt
root/tree/dataframe/LoopSUSYFrame/CMakeLists.txt
root/tree/dataframe/RNTupleDSBenchmarks.cxx
root/tree/dataframe/wmass/CMakeLists.txt
root/tree/tree/CMakeLists.txt
root/tree/treeplayer/CMakeLists.txt

More detail in the commit descriptions.

Fix rootbench for build configurations without RDataFrame

---

root/roofit/CMakeLists.txt
root/roofit/atlas-benchmarks/CMakeLists.txt
root/roofit/atlas-benchmarks/download_workspaces.sh
root/roofit/atlas-benchmarks/roofitAtlasHiggsBenchmark.cxx
root/roofit/atlas-benchmarks/run_benchmarks.sh

Add the benchmarks developed in the December 2021 hackathon with ATLAS.

[RF] Add RooFit ATLAS benchmarks

---

root/roofit/roofit/RooFitUnBinnedBenchmarks.cxx
root/roofit/roofit/benchRooFitBackends_make_plot.py

This commit brings in the exact code that was used to produce results presented at CHEP 2023:
https://indico.jlab.org/event/459/contributions/11570/

[RF] Update RooFit backend benchmarks to CHEP 2023 state

---

root/roofit/roofit/BenchmarkUtils.h
root/roofit/roofit/CMakeLists.txt
root/roofit/roofit/benchCodeSquashAD.cxx

Add a simple minimization benchmark for RooFuncWrapper with AD.

[RF] Add initial RooFit-AD benchmarks.

---

root/roofit/atlas-benchmarks/roofitAtlasHiggsBenchmark.cxx
root/roofit/roofit/benchCodeSquashAD.cxx

This is to build `rootbench` again with ROOT master

[RF] Update `benchCodeSquashAD` to new interfaces

---

root/roofit/atlas-benchmarks/roofitAtlasHiggsBenchmark.cxx

Also do minimization in the ATLAS benchmarks, and in particular do it also with the codegen + AD backend

[RF] Update ATLAS benchmarks to also do minimization with codegen AD
